import { Activity, ArrowRight, BellRing, Building2, ChevronRight, Gauge, Globe2, Radar, ShieldCheck, TrendingDown, TrendingUp } from 'lucide-react';
import { amplifiers, buffers, earlyWarnings, headlineMetrics, insights, macroRegime, sectorExposure, shocks, stressIndex, transmissionChannels } from '@/lib/data';
import { Panel, Pill, SectionHeading } from '@/components/ui';
function shockTone(level: string): 'danger' | 'warn' | 'success' | 'neutral' {
  if (level === 'High') return 'danger';
  if (level === 'Elevated') return 'warn';
  if (level === 'Moderate') return 'success';
  return 'neutral';
}
export default function HomePage() {
  return (
    <main>
      <header className="border-b border-slate-800/80 bg-slate-950/70 backdrop-blur">
        <div className="container-shell flex items-center justify-between py-4">
          <div><p className="text-lg font-semibold tracking-tight text-white">MacroLab Singapore</p><p className="text-xs uppercase tracking-[0.24em] text-slate-400">Geo-Economic Observatory</p></div>
          <nav className="hidden gap-6 text-sm text-slate-300 md:flex"><a href="#stress">Stress Index</a><a href="#shocks">Shock Tracker</a><a href="#channels">Transmission</a><a href="#sectors">Sector Exposure</a><a href="#api">API Surface</a></nav>
        </div>
      </header>
      <section className="container-shell grid gap-6 py-10 lg:grid-cols-12 lg:py-14">
        <Panel className="p-8 lg:col-span-7">
          <div className="space-y-5">
            <Pill tone="warn">Deployable v2 · API routes · schema-ready</Pill>
            <h1 className="max-w-3xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">Track global shocks, explain transmission, and surface sector-level consequences for Singapore.</h1>
            <p className="max-w-2xl text-base leading-7 text-slate-300">This version upgrades the homepage scaffold into a developer-deployable platform foundation with route handlers, typed domain schemas, mock data contracts, and Claude Skills automation scaffolding aligned to the MacroLab technical blueprint.</p>
            <div className="flex flex-wrap gap-3"><a className="inline-flex items-center rounded-xl bg-white px-4 py-2 text-sm font-medium text-slate-950" href="#shocks">View Shock Tracker <ArrowRight className="ml-2 h-4 w-4" /></a><a className="inline-flex items-center rounded-xl border border-slate-700 px-4 py-2 text-sm font-medium text-white" href="/dashboard">Open Data Dictionary</a></div>
          </div>
        </Panel>
        <Panel className="p-6 lg:col-span-5" id="stress">
          <div className="flex items-start justify-between"><div><p className="kicker">Current state</p><h2 className="mt-2 text-2xl font-semibold text-white">Singapore Macro Regime</h2><p className="mt-2 text-sm leading-6 text-slate-300">{macroRegime.summary}</p></div><Gauge className="h-6 w-6 text-red-400" /></div>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">{headlineMetrics.map((metric) => <div key={metric.label} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><p className="text-sm text-slate-400">{metric.label}</p><p className="metric-value mt-2">{metric.value}</p><p className="mt-2 text-xs font-medium text-slate-400">{metric.delta}</p></div>)}</div>
          <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center justify-between text-sm"><span className="text-slate-300">Stress status</span><Pill tone="warn">{stressIndex.status}</Pill></div><div className="mt-4 space-y-3">{stressIndex.components.map((component) => <div key={component.label}><div className="mb-1 flex justify-between text-xs text-slate-400"><span>{component.label}</span><span>{component.value}</span></div><div className="h-2 rounded-full bg-slate-800"><div className="h-2 rounded-full bg-gradient-to-r from-amber-400 to-red-500" style={{ width: `${component.value}%` }} /></div></div>)}</div></div>
        </Panel>
      </section>
      <section className="container-shell pb-10" id="shocks"><SectionHeading kicker="Shock tracker" title="Active global shocks" description="A four-card view of the major global disturbances currently shaping the Singapore outlook, aligned to the MacroLab shock taxonomy." /><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{shocks.map((shock) => <Panel key={shock.id} className="p-5"><div className="flex items-start justify-between gap-3"><Globe2 className="mt-1 h-5 w-5 text-slate-300" /><Pill tone={shockTone(shock.level)}>{shock.level}</Pill></div><h3 className="mt-4 text-lg font-semibold text-white">{shock.name}</h3><p className="mt-2 text-sm text-slate-400">{shock.category}</p><div className="mt-4 rounded-xl border border-slate-800 bg-slate-950/70 p-3 text-sm text-slate-300"><p className="font-medium text-white">Primary channel</p><p className="mt-1">{shock.transmissionChannel}</p></div><p className="mt-4 text-sm leading-6 text-slate-300">{shock.implication}</p></Panel>)}</div></section>
      <section className="container-shell pb-10" id="channels"><SectionHeading kicker="Transmission architecture" title="How shocks move through the economy" description="The platform follows the causal narrative set by the framework: Global Shock -> Transmission Channels -> Macro Regime -> Sector Impact -> Business Outcomes." /><div className="mt-6 grid gap-4 lg:grid-cols-12"><Panel className="p-6 lg:col-span-7"><div className="flex items-center gap-3"><Radar className="h-5 w-5 text-red-400" /><h3 className="text-lg font-semibold text-white">Transmission channels</h3></div><div className="mt-5 space-y-4">{transmissionChannels.map((channel) => <div key={channel.id} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-semibold text-white">{channel.title}</p><p className="mt-1 text-sm leading-6 text-slate-300">{channel.summary}</p></div><ChevronRight className="mt-1 h-4 w-4 text-slate-500" /></div><div className="mt-3 flex flex-wrap gap-2">{channel.indicators.map((indicator) => <Pill key={indicator}>{indicator}</Pill>)}</div></div>)}</div></Panel><div className="grid gap-4 lg:col-span-5"><Panel className="p-6"><div className="flex items-center gap-3"><TrendingDown className="h-5 w-5 text-amber-300" /><h3 className="text-lg font-semibold text-white">Amplifiers</h3></div><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{amplifiers.map((item) => <li key={item} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3">{item}</li>)}</ul></Panel><Panel className="p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-300" /><h3 className="text-lg font-semibold text-white">Buffers</h3></div><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{buffers.map((item) => <li key={item} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3">{item}</li>)}</ul></Panel></div></div></section>
      <section className="container-shell pb-10" id="sectors"><SectionHeading kicker="Sector dashboard" title="Sector exposure to macro transmission" description="This section prioritises sector-level consequences so business leaders, SMEs, and trade associations can see where shocks are likely to bite first." /><Panel className="mt-6 p-6"><div className="space-y-5">{sectorExposure.map((row) => <div key={row.sector} className="grid gap-3 lg:grid-cols-[280px_1fr_220px] lg:items-center"><div><p className="font-medium text-white">{row.sector}</p><p className="mt-1 text-sm text-slate-400">{row.outlook}</p></div><div className="h-3 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-amber-400 via-red-400 to-red-500" style={{ width: `${row.exposure}%` }} /></div><div className="rounded-xl border border-slate-800 bg-slate-950/70 px-4 py-3"><div className="flex items-center justify-between gap-3"><span className="text-sm text-slate-300">Exposure score</span><span className="text-sm font-semibold text-white">{row.exposure} · {row.tag}</span></div><p className="mt-2 text-xs leading-5 text-slate-400">{row.drivers.join(' · ')}</p></div></div>)}</div></Panel></section>
      <section className="container-shell grid gap-4 pb-10 lg:grid-cols-12"><Panel className="p-6 lg:col-span-5"><div className="flex items-center gap-3"><BellRing className="h-5 w-5 text-red-400" /><h3 className="text-lg font-semibold text-white">Early warning signals</h3></div><ul className="mt-4 space-y-3 text-sm leading-6 text-slate-300">{earlyWarnings.map((warning) => <li key={warning} className="rounded-xl border border-slate-800 bg-slate-950/70 p-3">{warning}</li>)}</ul></Panel><Panel className="p-6 lg:col-span-7"><div className="flex items-center gap-3"><Activity className="h-5 w-5 text-sky-300" /><h3 className="text-lg font-semibold text-white">AI-assisted insights feed</h3></div><div className="mt-4 space-y-4">{insights.map((item, index) => <div key={item.id} className="rounded-xl border border-slate-800 bg-slate-950/70 p-4"><div className="flex items-center justify-between gap-3"><p className="text-base font-semibold text-white">{item.title}</p><span className="text-xs uppercase tracking-[0.24em] text-slate-500">Signal {index + 1}</span></div><p className="mt-2 text-sm leading-6 text-slate-300">{item.summary}</p></div>)}</div></Panel></section>
      <section className="container-shell pb-14" id="api"><Panel className="grid gap-6 p-6 lg:grid-cols-3"><div><div className="flex items-center gap-3"><Building2 className="h-5 w-5 text-slate-300" /><h3 className="text-lg font-semibold text-white">Deployable routes</h3></div><p className="mt-3 text-sm leading-6 text-slate-300">Includes route handlers for health, shocks, stress index, macro regime, sector exposure, indicators, transmission channels, and insights.</p></div><div><div className="flex items-center gap-3"><TrendingUp className="h-5 w-5 text-slate-300" /><h3 className="text-lg font-semibold text-white">Typed data contracts</h3></div><p className="mt-3 text-sm leading-6 text-slate-300">Zod schemas define the platform domain objects so live ETL jobs can replace the current demo payloads without rewiring the UI.</p></div><div><div className="flex items-center gap-3"><Radar className="h-5 w-5 text-slate-300" /><h3 className="text-lg font-semibold text-white">Claude Skills scaffolding</h3></div><p className="mt-3 text-sm leading-6 text-slate-300">Skills folders are included for shock classification, regime scoring, insight drafting, and sector scoring so 80 percent of the workflow can be automated.</p></div></Panel></section>
    </main>
  );
}
